showAlertMessageWithException: renamed to showErrorAlertWithException:; showAlertMessage:withTitle:withSettings: renamed to showAlertWithTitle:message:andSettings: